### ISSUE TITLE
SAP CEC Fallback Channel cannot be selected

### ISSUE THREAD

**Issue by dannyboy2k** [RecastAI/Recast.AI#65] opened 2018-08-17 14:25 UTC
Hey,

when i try to select my SAP CEC Fallbackchannel in a skill the dropdownfield disappears and i can't save the Changes. It seems to be a Problem with loading the Groups (which by the way cannot be configured) as i can see a 403 request in the Network Tab of my browser after selecting the channel which looks like this:

https://api.recast.ai/connect/v1/users/{...}breathtaking-cec-channel/redirection_groups

and the response from this request is:

Request can not be processed without authentication

Any help is appreciated.

**Comment by ftriquet** [comment] 2018-08-17 21:14
Hello, 
What are your rights on the bot? Are you owner, admin/member of an organization, or collaborator to this bot?

**Comment by dannyboy2k** [comment] 2018-08-20 06:11
Hi,

a am a member of the organization the bot belongs to.

**Comment by ftriquet** [comment] 2018-08-20 21:04
Ok thank you. The problem is identified. It's a permission issue with organizations. We'll fix it a soon as possible.

**Comment by sathianarayananh** [comment] 2018-08-24 04:16
I too face same issue. But I don't see 403 for any request. Instead the service returns empty redirection_groups.

**Comment by ftriquet** [comment] 2018-08-28 21:33
Hello, I'm happy to inform you that we fixed two issues regarding fallback actions:
1) Permission problem when working with a organization bot
2) Backend returning no redirection groups

Everything is fixed in production now. Let us know if you still encounter any issues with it

**Comment by sathianarayananh** [comment] 2018-08-29 04:11
Thanks for the update. I can select a group now to redirect. But the fallback to CEC doesn't happen. I don't receive any chat request in CEC.

**Comment by dannyboy2k** [comment] 2018-08-29 06:06
I can confirm that this bug is fixed. thanks for the update. But i can also confirm the issue #71  of sathianarayananh when the fallback is triggered there is no incoming chat request in our CEC.

**Comment by ftriquet** [comment] 2018-08-29 06:09
Ok thank you I reopen the issue and we'll figure it out

**Closed** 2018-08-29 20:53 UTC
